# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
#
# See Documentation for more information:
# https://docs.powersync.com/usage/sync-rules
#
# Note that changes to this file are not watched.
# The service needs to be restarted for changes to take effect.

bucket_definitions:
  user_workouts:
    # Separate bucket per workout
    parameters: select id as workout_id from workouts where user_id = request.user_id()
    data:
      - select * from workouts where id = bucket.workout_id
