# https://github.com/supabase/setup-cli?tab=readme-ov-file#advanced-usage
name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/deploy-migrations.yml'

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Supabase Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PROJECT_ID: giaxxhmxhlbsijcrvouc

        steps:
          - uses: supabase/setup-cli@v1
          - run: supabase link --project-ref $PROJECT_ID
          - run: supabase db push
